#! /bin/bash

sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2> /dev/null &

# Check Homebrew is installed
command -v brew >/dev/null 2>&1 || { echo "Installing brew..."; ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; }

brew tap homebrew/php
brew tap homebrew/versions

brew update
brew upgrade

# Install PHP stuff
brew install php54-memcache
brew install php54-xdebug
brew install phpmyadmin
brew install libmemcached

# Install Java utils
brew install gradle
brew install maven
brew install scala210
brew link --force scala210

# Bash utils
brew install bash-completion

brew install git

brew install imagemagick
brew install antiword
brew install kdiff3
brew install mysql
brew install node
brew install python
brew install pdftohtml
brew install pwgen
brew install tesseract
brew install wget

brew cleanup
