#! /bin/bash

sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2> /dev/null &

# Check Homebrew is installed
command -v brew >/dev/null 2>&1 || { echo "Installing brew..."; ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; }

brew tap homebrew/versions

brew update
brew upgrade

# Bash utils
brew install bash-completion

# Other
brew install git
brew install imagemagick
brew install kdiff3
brew install node
brew install wget

brew cleanup
