#! /bin/bash

sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2> /dev/null &

# Check Homebrew is installed
command -v brew >/dev/null 2>&1 || { echo "Installing brew..."; ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; }

brew tap homebrew/php
brew tap homebrew/versions
brew tap homebrew/python

brew update
brew upgrade

# Install PHP stuff
# PHP 5.4
brew install php54
brew install php54-memcache
brew install php54-xdebug
brew install php54-mongo

# PHP 5.5
brew install php55
brew install php55-memcache
brew install php55-memcached
brew install php55-xdebug
brew install php55-mongo

brew install phpmyadmin

# Install Java utils
brew install gradle
brew install maven
brew install scala210
brew link --force scala210

# Bash utils
brew install bash-completion

# Other
brew install antiword
brew install git
brew install imagemagick
brew install kdiff3
brew install memcached
brew install mysql
brew install node
brew install pngcheck
brew install poppler
brew install pwgen
brew install python
brew install rbenv
brew install sqlite
brew install tesseract
brew install wget
brew install zlib
brew install zookeeper

brew cleanup
