#! /bin/bash

alias ls="ls -G"
alias l='ls'
alias ll='ls -la'
alias path='echo $PATH | tr ":" "\n" | sort'
alias clr='clear;echo "Currently logged in on $(tty), as $(whoami) in directory $(pwd)."'
alias cls='clr'
alias idea="open -a 'Intellij IDEA'"
alias sublime='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias st='sublime'
alias p='cd ~/projekty'
alias cup='composer update'
alias cin='composer install'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'

alias dotfiles='sublime ~/.dotfiles'
alias hosts='sudo sublime /etc/hosts'

# Git
alias gis='git status '
alias gic='git checkout -- '
alias inmaster='git fetch -q && git branch -r --merged origin/master'

# Mac
alias show="defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder"
