#! /bin/bash

alias ls="ls -G"
alias path='echo $PATH | tr ":" "\n" | sort'
alias clr='clear;echo "Currently logged in on $(tty), as $(whoami) in directory $(pwd)."'
alias cls='clr'
alias scala="JAVA_HOME=`/usr/libexec/java_home -v 1.7` $(brew --prefix scala29)/bin/scala"
alias st='open -a "Sublime Text 2"'
alias p='cd ~/projekty'
alias pnms='cd ~/projekty/NMS/nms'
alias pom='cd ~/projekty/AOM/offer-manager'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'

# Git
alias gis='git status '
alias gic='git checkout -- '

alias show="defaults write com.apple.Finder AppleShowAllFiles YES && killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles NO && killall Finder"