#! /bin/bash

BASH_SECRET_FILE='~/.bash_secret'
[ -r "$BASH_SECRET_FILE" ] && [ -f "$BASH_SECRET_FILE" ] && source "$BASH_SECRET_FILE";

# Node modules
export NODE_PATH=/usr/local/lib/node_modules/

PATH=$HOME/bin:$PATH
PATH=/usr/local/bin:/usr/local/sbin:$PATH;
export PATH;
