#! /bin/bash

BASH_SECRET_FILE='~/.bash_secret'
[ -r "$BASH_SECRET_FILE" ] && [ -f "$BASH_SECRET_FILE" ] && source "$BASH_SECRET_FILE";

# Java
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

PATH=$HOME/bin:$PATH
PATH=/usr/local/bin:/usr/local/sbin:$PATH;
export PATH;
