#! /bin/bash

BASH_SECRET_FILE='~/.bash_secret'
[ -r "$BASH_SECRET_FILE" ] && [ -f "$BASH_SECRET_FILE" ] && source "$BASH_SECRET_FILE";

# Java
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

# Oracle variables
export DYLD_LIBRARY_PATH=$ORACLE_HOME
export OCI_HOME=$ORACLE_HOME
export OCI_LIB_DIR=$ORACLE_HOME
export OCI_INCLUDE_DIR=$ORACLE_HOME/sdk/include
export OCI_VERSION=11
export NLS_LANG=.UTF8

# Node modules
export NODE_PATH=/usr/local/lib/node_modules/

PATH="$(brew --prefix php54)/bin:$PATH";
PATH=$HOME/bin:$PATH
PATH=/usr/local/bin:/usr/local/sbin:$PATH;
PATH=$PATH:$ORACLE_HOME;
export PATH;
